apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forenscope-output
  namespace: forenscope
spec:
  accessModes: [ReadWriteMany]
  storageClassName: standard
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forenscope-weights
  namespace: forenscope
spec:
  accessModes: [ReadOnlyMany]
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
