apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certainaity-output
  namespace: certainaity
spec:
  accessModes: [ReadWriteMany]
  storageClassName: standard
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certainaity-weights
  namespace: certainaity
spec:
  accessModes: [ReadOnlyMany]
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
